import type { Metadata } from "next";
import { Chakra_Petch, Geist_Mono } from "next/font/google";
import "../styles/globals.scss";
import SmoothScrollProvider from "@/components/smooth-scroll-provider";
import CustomCursor from "@/components/custom-cursor";
import ClickSpark from "@/components/ClickSpark";

const chakraPetch = Chakra_Petch({
  variable: "--font-chakra-petch",
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "<I am Gui />",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const savedTheme = localStorage.getItem('theme');
                const prefersDark = savedTheme === 'dark' || (!savedTheme && true);
                if (prefersDark) {
                  document.documentElement.classList.add('dark');
                } else {
                  document.documentElement.classList.remove('dark');
                }
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${chakraPetch.variable} ${geistMono.variable} antialiased`}
      >
        <CustomCursor />

        {/* <SpinningText
          data-cursor="pointer"
          className="fixed bottom-2 right-2 z-50 cursor-pointer w-24 h-24 text-white text-xs font-light"
          duration={30}
          radius={5}
        >
          scroll top • scroll top • scroll top •
        </SpinningText> */}

        <ClickSpark
          sparkColor="#fff"
          sparkSize={16}
          sparkRadius={30}
          sparkCount={8}
          duration={400}
        >
          <SmoothScrollProvider>{children}</SmoothScrollProvider>
        </ClickSpark>
      </body>
    </html>
  );
}
